Document: enumiax
Title: Debian enumiax Manual
Author: <insert document author here>
Abstract: This manual describes what enumiax is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/enumiax/enumiax.sgml.gz

Format: postscript
Files: /usr/share/doc/enumiax/enumiax.ps.gz

Format: text
Files: /usr/share/doc/enumiax/enumiax.text.gz

Format: HTML
Index: /usr/share/doc/enumiax/html/index.html
Files: /usr/share/doc/enumiax/html/*.html
